# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/action/action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/action/action.proto',
  package='action',
  syntax='proto3',
  serialized_options=_b('Z/github.com/tobiasfriden/dmc-server/proto/action'),
  serialized_pb=_b('\n\x19proto/action/action.proto\x12\x06\x61\x63tion\"\x88\x02\n\x07Payload\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.action.Payload.Type\x12&\n\x06status\x18\x02 \x01(\x0e\x32\x16.action.Payload.Status\x12\x0b\n\x03lat\x18\x03 \x01(\x02\x12\x0b\n\x03lng\x18\x04 \x01(\x02\x12\x0b\n\x03\x61lt\x18\x05 \x01(\x02\x12\x0e\n\x06\x65rrMsg\x18\x06 \x01(\t\"Y\n\x04Type\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04GOTO\x10\x01\x12\x08\n\x04LAND\x10\x02\x12\x0b\n\x07TAKEOFF\x10\x03\x12\x0c\n\x08\x46\x41ILSAFE\x10\x04\x12\n\n\x06LOITER\x10\x05\x12\x0c\n\x08SET_HOME\x10\x06\"\x1f\n\x06Status\x12\x08\n\x04\x46\x41IL\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x42\x31Z/github.com/tobiasfriden/dmc-server/proto/actionb\x06proto3')
)



_PAYLOAD_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='action.Payload.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOTO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAKEOFF', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILSAFE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOITER', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_HOME', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=180,
  serialized_end=269,
)
_sym_db.RegisterEnumDescriptor(_PAYLOAD_TYPE)

_PAYLOAD_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='action.Payload.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=271,
  serialized_end=302,
)
_sym_db.RegisterEnumDescriptor(_PAYLOAD_STATUS)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='action.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='action.Payload.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='action.Payload.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='action.Payload.lat', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='action.Payload.lng', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt', full_name='action.Payload.alt', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='action.Payload.errMsg', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PAYLOAD_TYPE,
    _PAYLOAD_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=302,
)

_PAYLOAD.fields_by_name['type'].enum_type = _PAYLOAD_TYPE
_PAYLOAD.fields_by_name['status'].enum_type = _PAYLOAD_STATUS
_PAYLOAD_TYPE.containing_type = _PAYLOAD
_PAYLOAD_STATUS.containing_type = _PAYLOAD
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'proto.action.action_pb2'
  # @@protoc_insertion_point(class_scope:action.Payload)
  ))
_sym_db.RegisterMessage(Payload)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
