# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/status/status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/status/status.proto',
  package='status',
  syntax='proto3',
  serialized_options=_b('Z/github.com/tobiasfriden/dmc-server/proto/status'),
  serialized_pb=_b('\n\x19proto/status/status.proto\x12\x06status\"\xc0\x01\n\x07Payload\x12\"\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x14.status.Payload.Code\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t\x12\x0b\n\x03\x61rm\x18\x03 \x01(\x08\x12\x0c\n\x04mode\x18\x04 \x01(\t\"f\n\x04\x43ode\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\x08\n\x04\x42OOT\x10\x01\x12\x0f\n\x0b\x43\x41LIBRATING\x10\x02\x12\x0b\n\x07STANDBY\x10\x03\x12\n\n\x06\x41\x43TIVE\x10\x04\x12\t\n\x05\x45RROR\x10\x05\x12\r\n\tEMERGENCY\x10\x06\x42\x31Z/github.com/tobiasfriden/dmc-server/proto/statusb\x06proto3')
)



_PAYLOAD_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='status.Payload.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALIBRATING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STANDBY', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMERGENCY', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=128,
  serialized_end=230,
)
_sym_db.RegisterEnumDescriptor(_PAYLOAD_CODE)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='status.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='status.Payload.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='status.Payload.errMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arm', full_name='status.Payload.arm', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='status.Payload.mode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PAYLOAD_CODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=230,
)

_PAYLOAD.fields_by_name['code'].enum_type = _PAYLOAD_CODE
_PAYLOAD_CODE.containing_type = _PAYLOAD
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'proto.status.status_pb2'
  # @@protoc_insertion_point(class_scope:status.Payload)
  ))
_sym_db.RegisterMessage(Payload)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
