# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/services/dronecache.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dmc.proto.cache import cache_pb2 as proto_dot_cache_dot_cache__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from dmc.proto import messages_pb2 as proto_dot_messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/services/dronecache.proto',
  package='dronecache',
  syntax='proto3',
  serialized_options=_b('Z<github.com/tobiasfriden/dmc-server/services/dronecache/proto'),
  serialized_pb=_b('\n\x1fproto/services/dronecache.proto\x12\ndronecache\x1a\x17proto/cache/cache.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14proto/messages.proto\".\n\x0cGetIdRequest\x12\x0f\n\x07\x64roneId\x18\x01 \x01(\t\x12\r\n\x05orgId\x18\x02 \x01(\t\".\n\rGetIdResponse\x12\x1d\n\x06result\x18\x01 \x01(\x0b\x32\r.cache.Record\"\x1e\n\rGetOrgRequest\x12\r\n\x05orgId\x18\x01 \x01(\t\"4\n\x0eGetOrgResponse\x12\"\n\x06result\x18\x01 \x01(\x0b\x32\x12.cache.RecordBatch\"3\n\x12GetDistanceRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\r\n\x05orgId\x18\x02 \x01(\t\"6\n\x13GetDistanceResponse\x12\x1f\n\x06result\x18\x01 \x03(\x0b\x32\x0f.cache.Distance2\x97\x02\n\nDroneCache\x12>\n\x05GetID\x12\x18.dronecache.GetIdRequest\x1a\x19.dronecache.GetIdResponse\"\x00\x12\x41\n\x06GetOrg\x12\x19.dronecache.GetOrgRequest\x1a\x1a.dronecache.GetOrgResponse\"\x00\x12\x34\n\x06Stream\x12\x16.google.protobuf.Empty\x1a\x0e.proto.Message\"\x00\x30\x01\x12P\n\x0bGetDistance\x12\x1e.dronecache.GetDistanceRequest\x1a\x1f.dronecache.GetDistanceResponse\"\x00\x42>Z<github.com/tobiasfriden/dmc-server/services/dronecache/protob\x06proto3')
  ,
  dependencies=[proto_dot_cache_dot_cache__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,proto_dot_messages__pb2.DESCRIPTOR,])




_GETIDREQUEST = _descriptor.Descriptor(
  name='GetIdRequest',
  full_name='dronecache.GetIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='droneId', full_name='dronecache.GetIdRequest.droneId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orgId', full_name='dronecache.GetIdRequest.orgId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=169,
)


_GETIDRESPONSE = _descriptor.Descriptor(
  name='GetIdResponse',
  full_name='dronecache.GetIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='dronecache.GetIdResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=217,
)


_GETORGREQUEST = _descriptor.Descriptor(
  name='GetOrgRequest',
  full_name='dronecache.GetOrgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orgId', full_name='dronecache.GetOrgRequest.orgId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=249,
)


_GETORGRESPONSE = _descriptor.Descriptor(
  name='GetOrgResponse',
  full_name='dronecache.GetOrgResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='dronecache.GetOrgResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=303,
)


_GETDISTANCEREQUEST = _descriptor.Descriptor(
  name='GetDistanceRequest',
  full_name='dronecache.GetDistanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='dronecache.GetDistanceRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orgId', full_name='dronecache.GetDistanceRequest.orgId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=356,
)


_GETDISTANCERESPONSE = _descriptor.Descriptor(
  name='GetDistanceResponse',
  full_name='dronecache.GetDistanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='dronecache.GetDistanceResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=412,
)

_GETIDRESPONSE.fields_by_name['result'].message_type = proto_dot_cache_dot_cache__pb2._RECORD
_GETORGRESPONSE.fields_by_name['result'].message_type = proto_dot_cache_dot_cache__pb2._RECORDBATCH
_GETDISTANCERESPONSE.fields_by_name['result'].message_type = proto_dot_cache_dot_cache__pb2._DISTANCE
DESCRIPTOR.message_types_by_name['GetIdRequest'] = _GETIDREQUEST
DESCRIPTOR.message_types_by_name['GetIdResponse'] = _GETIDRESPONSE
DESCRIPTOR.message_types_by_name['GetOrgRequest'] = _GETORGREQUEST
DESCRIPTOR.message_types_by_name['GetOrgResponse'] = _GETORGRESPONSE
DESCRIPTOR.message_types_by_name['GetDistanceRequest'] = _GETDISTANCEREQUEST
DESCRIPTOR.message_types_by_name['GetDistanceResponse'] = _GETDISTANCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetIdRequest = _reflection.GeneratedProtocolMessageType('GetIdRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETIDREQUEST,
  __module__ = 'proto.services.dronecache_pb2'
  # @@protoc_insertion_point(class_scope:dronecache.GetIdRequest)
  ))
_sym_db.RegisterMessage(GetIdRequest)

GetIdResponse = _reflection.GeneratedProtocolMessageType('GetIdResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETIDRESPONSE,
  __module__ = 'proto.services.dronecache_pb2'
  # @@protoc_insertion_point(class_scope:dronecache.GetIdResponse)
  ))
_sym_db.RegisterMessage(GetIdResponse)

GetOrgRequest = _reflection.GeneratedProtocolMessageType('GetOrgRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETORGREQUEST,
  __module__ = 'proto.services.dronecache_pb2'
  # @@protoc_insertion_point(class_scope:dronecache.GetOrgRequest)
  ))
_sym_db.RegisterMessage(GetOrgRequest)

GetOrgResponse = _reflection.GeneratedProtocolMessageType('GetOrgResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETORGRESPONSE,
  __module__ = 'proto.services.dronecache_pb2'
  # @@protoc_insertion_point(class_scope:dronecache.GetOrgResponse)
  ))
_sym_db.RegisterMessage(GetOrgResponse)

GetDistanceRequest = _reflection.GeneratedProtocolMessageType('GetDistanceRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETDISTANCEREQUEST,
  __module__ = 'proto.services.dronecache_pb2'
  # @@protoc_insertion_point(class_scope:dronecache.GetDistanceRequest)
  ))
_sym_db.RegisterMessage(GetDistanceRequest)

GetDistanceResponse = _reflection.GeneratedProtocolMessageType('GetDistanceResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETDISTANCERESPONSE,
  __module__ = 'proto.services.dronecache_pb2'
  # @@protoc_insertion_point(class_scope:dronecache.GetDistanceResponse)
  ))
_sym_db.RegisterMessage(GetDistanceResponse)


DESCRIPTOR._options = None

_DRONECACHE = _descriptor.ServiceDescriptor(
  name='DroneCache',
  full_name='dronecache.DroneCache',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=415,
  serialized_end=694,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetID',
    full_name='dronecache.DroneCache.GetID',
    index=0,
    containing_service=None,
    input_type=_GETIDREQUEST,
    output_type=_GETIDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetOrg',
    full_name='dronecache.DroneCache.GetOrg',
    index=1,
    containing_service=None,
    input_type=_GETORGREQUEST,
    output_type=_GETORGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Stream',
    full_name='dronecache.DroneCache.Stream',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=proto_dot_messages__pb2._MESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDistance',
    full_name='dronecache.DroneCache.GetDistance',
    index=3,
    containing_service=None,
    input_type=_GETDISTANCEREQUEST,
    output_type=_GETDISTANCERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DRONECACHE)

DESCRIPTOR.services_by_name['DroneCache'] = _DRONECACHE

# @@protoc_insertion_point(module_scope)
