# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from dmc.proto.services import drone_pb2 as proto_dot_services_dot_drone__pb2


class DroneStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Authorize = channel.unary_unary(
        '/drone.Drone/Authorize',
        request_serializer=proto_dot_services_dot_drone__pb2.AuthRequest.SerializeToString,
        response_deserializer=proto_dot_services_dot_drone__pb2.AuthResponse.FromString,
        )
    self.GetID = channel.unary_unary(
        '/drone.Drone/GetID',
        request_serializer=proto_dot_services_dot_drone__pb2.GetIDRequest.SerializeToString,
        response_deserializer=proto_dot_services_dot_drone__pb2.GetIDResponse.FromString,
        )
    self.Register = channel.unary_unary(
        '/drone.Drone/Register',
        request_serializer=proto_dot_services_dot_drone__pb2.RegisterRequest.SerializeToString,
        response_deserializer=proto_dot_services_dot_drone__pb2.RegisterResponse.FromString,
        )
    self.SetIMSI = channel.unary_unary(
        '/drone.Drone/SetIMSI',
        request_serializer=proto_dot_services_dot_drone__pb2.SetImsiRequest.SerializeToString,
        response_deserializer=proto_dot_services_dot_drone__pb2.SetImsiResponse.FromString,
        )
    self.Find = channel.unary_unary(
        '/drone.Drone/Find',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=proto_dot_services_dot_drone__pb2.FindDronesResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/drone.Drone/Delete',
        request_serializer=proto_dot_services_dot_drone__pb2.DeleteRequest.SerializeToString,
        response_deserializer=proto_dot_services_dot_drone__pb2.DeleteResponse.FromString,
        )


class DroneServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Authorize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetIMSI(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Find(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DroneServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Authorize': grpc.unary_unary_rpc_method_handler(
          servicer.Authorize,
          request_deserializer=proto_dot_services_dot_drone__pb2.AuthRequest.FromString,
          response_serializer=proto_dot_services_dot_drone__pb2.AuthResponse.SerializeToString,
      ),
      'GetID': grpc.unary_unary_rpc_method_handler(
          servicer.GetID,
          request_deserializer=proto_dot_services_dot_drone__pb2.GetIDRequest.FromString,
          response_serializer=proto_dot_services_dot_drone__pb2.GetIDResponse.SerializeToString,
      ),
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=proto_dot_services_dot_drone__pb2.RegisterRequest.FromString,
          response_serializer=proto_dot_services_dot_drone__pb2.RegisterResponse.SerializeToString,
      ),
      'SetIMSI': grpc.unary_unary_rpc_method_handler(
          servicer.SetIMSI,
          request_deserializer=proto_dot_services_dot_drone__pb2.SetImsiRequest.FromString,
          response_serializer=proto_dot_services_dot_drone__pb2.SetImsiResponse.SerializeToString,
      ),
      'Find': grpc.unary_unary_rpc_method_handler(
          servicer.Find,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=proto_dot_services_dot_drone__pb2.FindDronesResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=proto_dot_services_dot_drone__pb2.DeleteRequest.FromString,
          response_serializer=proto_dot_services_dot_drone__pb2.DeleteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'drone.Drone', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
