# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/services/launcher.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/services/launcher.proto',
  package='launcher',
  syntax='proto3',
  serialized_options=_b('Z:github.com/tobiasfriden/dmc-server/services/launcher/proto'),
  serialized_pb=_b('\n\x1dproto/services/launcher.proto\x12\x08launcher\x1a\x19google/protobuf/any.proto2F\n\x08Launcher\x12:\n\x06Stream\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00(\x01\x30\x01\x42<Z:github.com/tobiasfriden/dmc-server/services/launcher/protob\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_LAUNCHER = _descriptor.ServiceDescriptor(
  name='Launcher',
  full_name='launcher.Launcher',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=70,
  serialized_end=140,
  methods=[
  _descriptor.MethodDescriptor(
    name='Stream',
    full_name='launcher.Launcher.Stream',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_any__pb2._ANY,
    output_type=google_dot_protobuf_dot_any__pb2._ANY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LAUNCHER)

DESCRIPTOR.services_by_name['Launcher'] = _LAUNCHER

# @@protoc_insertion_point(module_scope)
