# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import messages_pb2 as proto_dot_messages__pb2
from proto.services import shell_pb2 as proto_dot_services_dot_shell__pb2


class ShellStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PilotStream = channel.unary_stream(
        '/shell.Shell/PilotStream',
        request_serializer=proto_dot_services_dot_shell__pb2.StreamRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.Message.FromString,
        )
    self.PilotLine = channel.unary_unary(
        '/shell.Shell/PilotLine',
        request_serializer=proto_dot_services_dot_shell__pb2.Line.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.DroneStream = channel.stream_stream(
        '/shell.Shell/DroneStream',
        request_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
        )


class ShellServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PilotStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PilotLine(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DroneStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ShellServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PilotStream': grpc.unary_stream_rpc_method_handler(
          servicer.PilotStream,
          request_deserializer=proto_dot_services_dot_shell__pb2.StreamRequest.FromString,
          response_serializer=proto_dot_messages__pb2.Message.SerializeToString,
      ),
      'PilotLine': grpc.unary_unary_rpc_method_handler(
          servicer.PilotLine,
          request_deserializer=proto_dot_services_dot_shell__pb2.Line.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'DroneStream': grpc.stream_stream_rpc_method_handler(
          servicer.DroneStream,
          request_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
          response_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'shell.Shell', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
