# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from dmc.proto.services import sim_pb2 as proto_dot_services_dot_sim__pb2


class SimStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Start = channel.unary_unary(
        '/sim.Sim/Start',
        request_serializer=proto_dot_services_dot_sim__pb2.StartRequest.SerializeToString,
        response_deserializer=proto_dot_services_dot_sim__pb2.StartResponse.FromString,
        )
    self.Stop = channel.unary_unary(
        '/sim.Sim/Stop',
        request_serializer=proto_dot_services_dot_sim__pb2.StopRequest.SerializeToString,
        response_deserializer=proto_dot_services_dot_sim__pb2.StopResponse.FromString,
        )
    self.Get = channel.unary_unary(
        '/sim.Sim/Get',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=proto_dot_services_dot_sim__pb2.GetResponse.FromString,
        )


class SimServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Start(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Stop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Start': grpc.unary_unary_rpc_method_handler(
          servicer.Start,
          request_deserializer=proto_dot_services_dot_sim__pb2.StartRequest.FromString,
          response_serializer=proto_dot_services_dot_sim__pb2.StartResponse.SerializeToString,
      ),
      'Stop': grpc.unary_unary_rpc_method_handler(
          servicer.Stop,
          request_deserializer=proto_dot_services_dot_sim__pb2.StopRequest.FromString,
          response_serializer=proto_dot_services_dot_sim__pb2.StopResponse.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=proto_dot_services_dot_sim__pb2.GetResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sim.Sim', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
