# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from dmc.proto.services import usercache_pb2 as proto_dot_services_dot_usercache__pb2


class UserCacheStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOrg = channel.unary_unary(
        '/usercache.UserCache/GetOrg',
        request_serializer=proto_dot_services_dot_usercache__pb2.GetOrgRequest.SerializeToString,
        response_deserializer=proto_dot_services_dot_usercache__pb2.GetOrgResponse.FromString,
        )


class UserCacheServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOrg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserCacheServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOrg': grpc.unary_unary_rpc_method_handler(
          servicer.GetOrg,
          request_deserializer=proto_dot_services_dot_usercache__pb2.GetOrgRequest.FromString,
          response_serializer=proto_dot_services_dot_usercache__pb2.GetOrgResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'usercache.UserCache', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
