# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/services/usercache.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/services/usercache.proto',
  package='usercache',
  syntax='proto3',
  serialized_options=_b('Z;github.com/tobiasfriden/dmc-server/services/usercache/proto'),
  serialized_pb=_b('\n\x1eproto/services/usercache.proto\x12\tusercache\"\x1e\n\rGetOrgRequest\x12\r\n\x05orgId\x18\x01 \x01(\t\"y\n\x0eGetOrgResponse\x12\x37\n\x07results\x18\x01 \x03(\x0b\x32&.usercache.GetOrgResponse.ResultsEntry\x1a.\n\x0cResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32L\n\tUserCache\x12?\n\x06GetOrg\x12\x18.usercache.GetOrgRequest\x1a\x19.usercache.GetOrgResponse\"\x00\x42=Z;github.com/tobiasfriden/dmc-server/services/usercache/protob\x06proto3')
)




_GETORGREQUEST = _descriptor.Descriptor(
  name='GetOrgRequest',
  full_name='usercache.GetOrgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orgId', full_name='usercache.GetOrgRequest.orgId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=75,
)


_GETORGRESPONSE_RESULTSENTRY = _descriptor.Descriptor(
  name='ResultsEntry',
  full_name='usercache.GetOrgResponse.ResultsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='usercache.GetOrgResponse.ResultsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='usercache.GetOrgResponse.ResultsEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=198,
)

_GETORGRESPONSE = _descriptor.Descriptor(
  name='GetOrgResponse',
  full_name='usercache.GetOrgResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='usercache.GetOrgResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETORGRESPONSE_RESULTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=198,
)

_GETORGRESPONSE_RESULTSENTRY.containing_type = _GETORGRESPONSE
_GETORGRESPONSE.fields_by_name['results'].message_type = _GETORGRESPONSE_RESULTSENTRY
DESCRIPTOR.message_types_by_name['GetOrgRequest'] = _GETORGREQUEST
DESCRIPTOR.message_types_by_name['GetOrgResponse'] = _GETORGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetOrgRequest = _reflection.GeneratedProtocolMessageType('GetOrgRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETORGREQUEST,
  __module__ = 'proto.services.usercache_pb2'
  # @@protoc_insertion_point(class_scope:usercache.GetOrgRequest)
  ))
_sym_db.RegisterMessage(GetOrgRequest)

GetOrgResponse = _reflection.GeneratedProtocolMessageType('GetOrgResponse', (_message.Message,), dict(

  ResultsEntry = _reflection.GeneratedProtocolMessageType('ResultsEntry', (_message.Message,), dict(
    DESCRIPTOR = _GETORGRESPONSE_RESULTSENTRY,
    __module__ = 'proto.services.usercache_pb2'
    # @@protoc_insertion_point(class_scope:usercache.GetOrgResponse.ResultsEntry)
    ))
  ,
  DESCRIPTOR = _GETORGRESPONSE,
  __module__ = 'proto.services.usercache_pb2'
  # @@protoc_insertion_point(class_scope:usercache.GetOrgResponse)
  ))
_sym_db.RegisterMessage(GetOrgResponse)
_sym_db.RegisterMessage(GetOrgResponse.ResultsEntry)


DESCRIPTOR._options = None
_GETORGRESPONSE_RESULTSENTRY._options = None

_USERCACHE = _descriptor.ServiceDescriptor(
  name='UserCache',
  full_name='usercache.UserCache',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=200,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOrg',
    full_name='usercache.UserCache.GetOrg',
    index=0,
    containing_service=None,
    input_type=_GETORGREQUEST,
    output_type=_GETORGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERCACHE)

DESCRIPTOR.services_by_name['UserCache'] = _USERCACHE

# @@protoc_insertion_point(module_scope)
