# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/services/user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import messages_pb2 as proto_dot_messages__pb2
from proto.mission import mission_pb2 as proto_dot_mission_dot_mission__pb2
from proto.action import action_pb2 as proto_dot_action_dot_action__pb2
from proto.control import control_pb2 as proto_dot_control_dot_control__pb2
from proto.launcher import launcher_pb2 as proto_dot_launcher_dot_launcher__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/services/user.proto',
  package='user',
  syntax='proto3',
  serialized_options=_b('Z6github.com/tobiasfriden/dmc-server/services/user/proto'),
  serialized_pb=_b('\n\x19proto/services/user.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14proto/messages.proto\x1a\x1bproto/mission/mission.proto\x1a\x19proto/action/action.proto\x1a\x1bproto/control/control.proto\x1a\x1dproto/launcher/launcher.proto\"D\n\x0eMissionRequest\x12\x0f\n\x07\x64roneID\x18\x01 \x01(\t\x12!\n\x07payload\x18\x02 \x01(\x0b\x32\x10.mission.Payload\"B\n\rActionRequest\x12\x0f\n\x07\x64roneID\x18\x01 \x01(\t\x12 \n\x07payload\x18\x02 \x01(\x0b\x32\x0f.action.Payload\"D\n\x0e\x43ontrolRequest\x12\x0f\n\x07\x64roneID\x18\x01 \x01(\t\x12!\n\x07payload\x18\x02 \x01(\x0b\x32\x10.control.Payload\"D\n\x0e\x43ommandRequest\x12\x12\n\nlauncherID\x18\x01 \x01(\t\x12\x1e\n\x03\x63md\x18\x02 \x01(\x0b\x32\x11.launcher.Command2\xa6\x02\n\x04User\x12\x34\n\x06Stream\x12\x16.google.protobuf.Empty\x1a\x0e.proto.Message\"\x00\x30\x01\x12\x39\n\x07Mission\x12\x14.user.MissionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x37\n\x06\x41\x63tion\x12\x13.user.ActionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x39\n\x07\x43ontrol\x12\x14.user.ControlRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x39\n\x07\x43ommand\x12\x14.user.CommandRequest\x1a\x16.google.protobuf.Empty\"\x00\x42\x38Z6github.com/tobiasfriden/dmc-server/services/user/protob\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,proto_dot_messages__pb2.DESCRIPTOR,proto_dot_mission_dot_mission__pb2.DESCRIPTOR,proto_dot_action_dot_action__pb2.DESCRIPTOR,proto_dot_control_dot_control__pb2.DESCRIPTOR,proto_dot_launcher_dot_launcher__pb2.DESCRIPTOR,])




_MISSIONREQUEST = _descriptor.Descriptor(
  name='MissionRequest',
  full_name='user.MissionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='droneID', full_name='user.MissionRequest.droneID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='user.MissionRequest.payload', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=270,
)


_ACTIONREQUEST = _descriptor.Descriptor(
  name='ActionRequest',
  full_name='user.ActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='droneID', full_name='user.ActionRequest.droneID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='user.ActionRequest.payload', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=338,
)


_CONTROLREQUEST = _descriptor.Descriptor(
  name='ControlRequest',
  full_name='user.ControlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='droneID', full_name='user.ControlRequest.droneID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='user.ControlRequest.payload', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=408,
)


_COMMANDREQUEST = _descriptor.Descriptor(
  name='CommandRequest',
  full_name='user.CommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='launcherID', full_name='user.CommandRequest.launcherID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='user.CommandRequest.cmd', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=478,
)

_MISSIONREQUEST.fields_by_name['payload'].message_type = proto_dot_mission_dot_mission__pb2._PAYLOAD
_ACTIONREQUEST.fields_by_name['payload'].message_type = proto_dot_action_dot_action__pb2._PAYLOAD
_CONTROLREQUEST.fields_by_name['payload'].message_type = proto_dot_control_dot_control__pb2._PAYLOAD
_COMMANDREQUEST.fields_by_name['cmd'].message_type = proto_dot_launcher_dot_launcher__pb2._COMMAND
DESCRIPTOR.message_types_by_name['MissionRequest'] = _MISSIONREQUEST
DESCRIPTOR.message_types_by_name['ActionRequest'] = _ACTIONREQUEST
DESCRIPTOR.message_types_by_name['ControlRequest'] = _CONTROLREQUEST
DESCRIPTOR.message_types_by_name['CommandRequest'] = _COMMANDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MissionRequest = _reflection.GeneratedProtocolMessageType('MissionRequest', (_message.Message,), dict(
  DESCRIPTOR = _MISSIONREQUEST,
  __module__ = 'proto.services.user_pb2'
  # @@protoc_insertion_point(class_scope:user.MissionRequest)
  ))
_sym_db.RegisterMessage(MissionRequest)

ActionRequest = _reflection.GeneratedProtocolMessageType('ActionRequest', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONREQUEST,
  __module__ = 'proto.services.user_pb2'
  # @@protoc_insertion_point(class_scope:user.ActionRequest)
  ))
_sym_db.RegisterMessage(ActionRequest)

ControlRequest = _reflection.GeneratedProtocolMessageType('ControlRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLREQUEST,
  __module__ = 'proto.services.user_pb2'
  # @@protoc_insertion_point(class_scope:user.ControlRequest)
  ))
_sym_db.RegisterMessage(ControlRequest)

CommandRequest = _reflection.GeneratedProtocolMessageType('CommandRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDREQUEST,
  __module__ = 'proto.services.user_pb2'
  # @@protoc_insertion_point(class_scope:user.CommandRequest)
  ))
_sym_db.RegisterMessage(CommandRequest)


DESCRIPTOR._options = None

_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='user.User',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=481,
  serialized_end=775,
  methods=[
  _descriptor.MethodDescriptor(
    name='Stream',
    full_name='user.User.Stream',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=proto_dot_messages__pb2._MESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Mission',
    full_name='user.User.Mission',
    index=1,
    containing_service=None,
    input_type=_MISSIONREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Action',
    full_name='user.User.Action',
    index=2,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Control',
    full_name='user.User.Control',
    index=3,
    containing_service=None,
    input_type=_CONTROLREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Command',
    full_name='user.User.Command',
    index=4,
    containing_service=None,
    input_type=_COMMANDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
