# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/telemetry/telemetry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/telemetry/telemetry.proto',
  package='telemetry',
  syntax='proto3',
  serialized_options=_b('Z2github.com/tobiasfriden/dmc-server/proto/telemetry'),
  serialized_pb=_b('\n\x1fproto/telemetry/telemetry.proto\x12\ttelemetry\"1\n\x08Position\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lng\x18\x02 \x01(\x02\x12\x0b\n\x03\x61lt\x18\x03 \x01(\x02\"\x1a\n\x07Heading\x12\x0f\n\x07heading\x18\x01 \x01(\x02\"i\n\x07\x42\x61ttery\x12\x14\n\x0c\x63\x65ll_voltage\x18\x01 \x03(\x02\x12\x0f\n\x07\x63urrent\x18\x02 \x01(\x02\x12\x12\n\npercentage\x18\x03 \x01(\x02\x12\x12\n\npsu_status\x18\x04 \x01(\x02\x12\x0f\n\x07voltage\x18\x05 \x01(\x02\"s\n\nConnection\x12\x13\n\x0bsat_visible\x18\x01 \x01(\x02\x12\x13\n\x0bsignal_bars\x18\x02 \x01(\x05\x12\x17\n\x0fsignal_strength\x18\x03 \x01(\x05\x12\x10\n\x08tx_bytes\x18\x04 \x01(\x03\x12\x10\n\x08rx_bytes\x18\x05 \x01(\x03\"+\n\x08Velocity\x12\x0f\n\x07\x61ngular\x18\x01 \x03(\x02\x12\x0e\n\x06linear\x18\x02 \x03(\x02\"\xcc\x01\n\x07Payload\x12%\n\x08position\x18\x01 \x01(\x0b\x32\x13.telemetry.Position\x12#\n\x07heading\x18\x02 \x01(\x0b\x32\x12.telemetry.Heading\x12#\n\x07\x62\x61ttery\x18\x03 \x01(\x0b\x32\x12.telemetry.Battery\x12)\n\nconnection\x18\x04 \x01(\x0b\x32\x15.telemetry.Connection\x12%\n\x08velocity\x18\x05 \x01(\x0b\x32\x13.telemetry.Velocity\"\xcf\x01\n\nLogPayload\x12%\n\x08position\x18\x01 \x01(\x0b\x32\x13.telemetry.Position\x12#\n\x07heading\x18\x02 \x01(\x0b\x32\x12.telemetry.Heading\x12#\n\x07\x62\x61ttery\x18\x03 \x01(\x0b\x32\x12.telemetry.Battery\x12)\n\nconnection\x18\x04 \x01(\x0b\x32\x15.telemetry.Connection\x12%\n\x08velocity\x18\x05 \x01(\x0b\x32\x13.telemetry.VelocityB4Z2github.com/tobiasfriden/dmc-server/proto/telemetryb\x06proto3')
)




_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='telemetry.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='telemetry.Position.lat', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='telemetry.Position.lng', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt', full_name='telemetry.Position.alt', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=95,
)


_HEADING = _descriptor.Descriptor(
  name='Heading',
  full_name='telemetry.Heading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heading', full_name='telemetry.Heading.heading', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=123,
)


_BATTERY = _descriptor.Descriptor(
  name='Battery',
  full_name='telemetry.Battery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cell_voltage', full_name='telemetry.Battery.cell_voltage', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current', full_name='telemetry.Battery.current', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percentage', full_name='telemetry.Battery.percentage', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='psu_status', full_name='telemetry.Battery.psu_status', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='telemetry.Battery.voltage', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=230,
)


_CONNECTION = _descriptor.Descriptor(
  name='Connection',
  full_name='telemetry.Connection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sat_visible', full_name='telemetry.Connection.sat_visible', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signal_bars', full_name='telemetry.Connection.signal_bars', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signal_strength', full_name='telemetry.Connection.signal_strength', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tx_bytes', full_name='telemetry.Connection.tx_bytes', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rx_bytes', full_name='telemetry.Connection.rx_bytes', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=347,
)


_VELOCITY = _descriptor.Descriptor(
  name='Velocity',
  full_name='telemetry.Velocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angular', full_name='telemetry.Velocity.angular', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linear', full_name='telemetry.Velocity.linear', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=392,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='telemetry.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='telemetry.Payload.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='telemetry.Payload.heading', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery', full_name='telemetry.Payload.battery', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connection', full_name='telemetry.Payload.connection', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='telemetry.Payload.velocity', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=599,
)


_LOGPAYLOAD = _descriptor.Descriptor(
  name='LogPayload',
  full_name='telemetry.LogPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='telemetry.LogPayload.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='telemetry.LogPayload.heading', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery', full_name='telemetry.LogPayload.battery', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connection', full_name='telemetry.LogPayload.connection', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='telemetry.LogPayload.velocity', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=602,
  serialized_end=809,
)

_PAYLOAD.fields_by_name['position'].message_type = _POSITION
_PAYLOAD.fields_by_name['heading'].message_type = _HEADING
_PAYLOAD.fields_by_name['battery'].message_type = _BATTERY
_PAYLOAD.fields_by_name['connection'].message_type = _CONNECTION
_PAYLOAD.fields_by_name['velocity'].message_type = _VELOCITY
_LOGPAYLOAD.fields_by_name['position'].message_type = _POSITION
_LOGPAYLOAD.fields_by_name['heading'].message_type = _HEADING
_LOGPAYLOAD.fields_by_name['battery'].message_type = _BATTERY
_LOGPAYLOAD.fields_by_name['connection'].message_type = _CONNECTION
_LOGPAYLOAD.fields_by_name['velocity'].message_type = _VELOCITY
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['Heading'] = _HEADING
DESCRIPTOR.message_types_by_name['Battery'] = _BATTERY
DESCRIPTOR.message_types_by_name['Connection'] = _CONNECTION
DESCRIPTOR.message_types_by_name['Velocity'] = _VELOCITY
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
DESCRIPTOR.message_types_by_name['LogPayload'] = _LOGPAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'proto.telemetry.telemetry_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.Position)
  ))
_sym_db.RegisterMessage(Position)

Heading = _reflection.GeneratedProtocolMessageType('Heading', (_message.Message,), dict(
  DESCRIPTOR = _HEADING,
  __module__ = 'proto.telemetry.telemetry_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.Heading)
  ))
_sym_db.RegisterMessage(Heading)

Battery = _reflection.GeneratedProtocolMessageType('Battery', (_message.Message,), dict(
  DESCRIPTOR = _BATTERY,
  __module__ = 'proto.telemetry.telemetry_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.Battery)
  ))
_sym_db.RegisterMessage(Battery)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTION,
  __module__ = 'proto.telemetry.telemetry_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.Connection)
  ))
_sym_db.RegisterMessage(Connection)

Velocity = _reflection.GeneratedProtocolMessageType('Velocity', (_message.Message,), dict(
  DESCRIPTOR = _VELOCITY,
  __module__ = 'proto.telemetry.telemetry_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.Velocity)
  ))
_sym_db.RegisterMessage(Velocity)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'proto.telemetry.telemetry_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.Payload)
  ))
_sym_db.RegisterMessage(Payload)

LogPayload = _reflection.GeneratedProtocolMessageType('LogPayload', (_message.Message,), dict(
  DESCRIPTOR = _LOGPAYLOAD,
  __module__ = 'proto.telemetry.telemetry_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.LogPayload)
  ))
_sym_db.RegisterMessage(LogPayload)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
