# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mission/mission.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/mission/mission.proto',
  package='mission',
  syntax='proto3',
  serialized_options=_b('Z0github.com/tobiasfriden/dmc-server/proto/mission'),
  serialized_pb=_b('\n\x1bproto/mission/mission.proto\x12\x07mission\"\xb2\x01\n\x08Waypoint\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.mission.Waypoint.Type\x12\x0b\n\x03lat\x18\x02 \x01(\x02\x12\x0b\n\x03lng\x18\x03 \x01(\x02\x12\x0b\n\x03\x61lt\x18\x04 \x01(\x02\x12\r\n\x05speed\x18\x07 \x01(\x02\"J\n\x04Type\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08WAYPOINT\x10\x01\x12\x0b\n\x07TAKEOFF\x10\x02\x12\x08\n\x04LAND\x10\x03\x12\x07\n\x03RTL\x10\x04\x12\n\n\x06LOITER\x10\x05\"-\n\x04Home\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lng\x18\x02 \x01(\x02\x12\x0b\n\x03\x61lt\x18\x03 \x01(\x02\"\xb0\x02\n\x07Payload\x12!\n\x03\x63md\x18\x01 \x01(\x0e\x32\x14.mission.Payload.Cmd\x12\x1b\n\x04home\x18\x02 \x01(\x0b\x32\r.mission.Home\x12\x0f\n\x07reached\x18\x03 \x01(\x05\x12$\n\twaypoints\x18\x04 \x03(\x0b\x32\x11.mission.Waypoint\x12\x0e\n\x06\x65rrMsg\x18\x05 \x01(\t\"\x9d\x01\n\x03\x43md\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03SET\x10\x01\x12\x0f\n\x0bSET_SUCCESS\x10\x02\x12\x0c\n\x08SET_FAIL\x10\x03\x12\t\n\x05START\x10\x04\x12\x11\n\rSTART_SUCCESS\x10\x05\x12\x0e\n\nSTART_FAIL\x10\x06\x12\r\n\tAUTH_FAIL\x10\x07\x12\x0b\n\x07REACHED\x10\x08\x12\x0c\n\x08SET_HOME\x10\t\x12\x0c\n\x08\x46INISHED\x10\nB2Z0github.com/tobiasfriden/dmc-server/proto/missionb\x06proto3')
)



_WAYPOINT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='mission.Waypoint.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WAYPOINT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAKEOFF', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAND', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RTL', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOITER', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=145,
  serialized_end=219,
)
_sym_db.RegisterEnumDescriptor(_WAYPOINT_TYPE)

_PAYLOAD_CMD = _descriptor.EnumDescriptor(
  name='Cmd',
  full_name='mission.Payload.Cmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_SUCCESS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_FAIL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START_SUCCESS', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START_FAIL', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTH_FAIL', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REACHED', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_HOME', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISHED', index=10, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=416,
  serialized_end=573,
)
_sym_db.RegisterEnumDescriptor(_PAYLOAD_CMD)


_WAYPOINT = _descriptor.Descriptor(
  name='Waypoint',
  full_name='mission.Waypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mission.Waypoint.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='mission.Waypoint.lat', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='mission.Waypoint.lng', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt', full_name='mission.Waypoint.alt', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='mission.Waypoint.speed', index=4,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WAYPOINT_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=219,
)


_HOME = _descriptor.Descriptor(
  name='Home',
  full_name='mission.Home',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='mission.Home.lat', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='mission.Home.lng', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt', full_name='mission.Home.alt', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=266,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='mission.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='mission.Payload.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='home', full_name='mission.Payload.home', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reached', full_name='mission.Payload.reached', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='mission.Payload.waypoints', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='mission.Payload.errMsg', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PAYLOAD_CMD,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=573,
)

_WAYPOINT.fields_by_name['type'].enum_type = _WAYPOINT_TYPE
_WAYPOINT_TYPE.containing_type = _WAYPOINT
_PAYLOAD.fields_by_name['cmd'].enum_type = _PAYLOAD_CMD
_PAYLOAD.fields_by_name['home'].message_type = _HOME
_PAYLOAD.fields_by_name['waypoints'].message_type = _WAYPOINT
_PAYLOAD_CMD.containing_type = _PAYLOAD
DESCRIPTOR.message_types_by_name['Waypoint'] = _WAYPOINT
DESCRIPTOR.message_types_by_name['Home'] = _HOME
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Waypoint = _reflection.GeneratedProtocolMessageType('Waypoint', (_message.Message,), dict(
  DESCRIPTOR = _WAYPOINT,
  __module__ = 'proto.mission.mission_pb2'
  # @@protoc_insertion_point(class_scope:mission.Waypoint)
  ))
_sym_db.RegisterMessage(Waypoint)

Home = _reflection.GeneratedProtocolMessageType('Home', (_message.Message,), dict(
  DESCRIPTOR = _HOME,
  __module__ = 'proto.mission.mission_pb2'
  # @@protoc_insertion_point(class_scope:mission.Home)
  ))
_sym_db.RegisterMessage(Home)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'proto.mission.mission_pb2'
  # @@protoc_insertion_point(class_scope:mission.Payload)
  ))
_sym_db.RegisterMessage(Payload)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
