# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/control/control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/control/control.proto',
  package='control',
  syntax='proto3',
  serialized_options=_b('Z0github.com/tobiasfriden/dmc-server/proto/control'),
  serialized_pb=_b('\n\x1bproto/control/control.proto\x12\x07\x63ontrol\"\xa1\x01\n\x07Payload\x12%\n\x03req\x18\x01 \x01(\x0e\x32\x18.control.Payload.Request\x12\x0e\n\x06userId\x18\x02 \x01(\t\"_\n\x07Request\x12\x08\n\x04\x46\x41IL\x10\x00\x12\x0c\n\x08TAKEOVER\x10\x01\x12\t\n\x05LEAVE\x10\x02\x12\n\n\x06\x41\x43\x43\x45PT\x10\x03\x12\x0b\n\x07\x44\x45\x43LINE\x10\x04\x12\t\n\x05\x43LEAR\x10\x05\x12\r\n\tMASTER_DC\x10\x06\x42\x32Z0github.com/tobiasfriden/dmc-server/proto/controlb\x06proto3')
)



_PAYLOAD_REQUEST = _descriptor.EnumDescriptor(
  name='Request',
  full_name='control.Payload.Request',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAKEOVER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAVE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCEPT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECLINE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLEAR', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MASTER_DC', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=107,
  serialized_end=202,
)
_sym_db.RegisterEnumDescriptor(_PAYLOAD_REQUEST)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='control.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req', full_name='control.Payload.req', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='control.Payload.userId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PAYLOAD_REQUEST,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=202,
)

_PAYLOAD.fields_by_name['req'].enum_type = _PAYLOAD_REQUEST
_PAYLOAD_REQUEST.containing_type = _PAYLOAD
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'proto.control.control_pb2'
  # @@protoc_insertion_point(class_scope:control.Payload)
  ))
_sym_db.RegisterMessage(Payload)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
