# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cache/cache.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.action import action_pb2 as proto_dot_action_dot_action__pb2
from proto.control import control_pb2 as proto_dot_control_dot_control__pb2
from proto.mission import mission_pb2 as proto_dot_mission_dot_mission__pb2
from proto.status import status_pb2 as proto_dot_status_dot_status__pb2
from proto.log import log_pb2 as proto_dot_log_dot_log__pb2
from proto.telemetry import telemetry_pb2 as proto_dot_telemetry_dot_telemetry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/cache/cache.proto',
  package='cache',
  syntax='proto3',
  serialized_options=_b('Z.github.com/tobiasfriden/dmc-server/proto/cache'),
  serialized_pb=_b('\n\x17proto/cache/cache.proto\x12\x05\x63\x61\x63he\x1a\x19proto/action/action.proto\x1a\x1bproto/control/control.proto\x1a\x1bproto/mission/mission.proto\x1a\x19proto/status/status.proto\x1a\x13proto/log/log.proto\x1a\x1fproto/telemetry/telemetry.proto\"K\n\x08\x44istance\x12\x0f\n\x07\x64roneId\x18\x01 \x01(\t\x12\x0f\n\x07otherId\x18\x02 \x01(\t\x12\x0e\n\x06master\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\"\xb9\x02\n\x06Record\x12\x1f\n\x06\x61\x63tion\x18\x01 \x01(\x0b\x32\x0f.action.Payload\x12!\n\x07\x63ontrol\x18\x02 \x01(\x0b\x32\x10.control.Payload\x12!\n\x07mission\x18\x03 \x01(\x0b\x32\x10.mission.Payload\x12\x1f\n\x06status\x18\x04 \x01(\x0b\x32\x0f.status.Payload\x12#\n\x03log\x18\x05 \x03(\x0b\x32\x16.cache.Record.LogEntry\x12%\n\ttelemetry\x18\x06 \x01(\x0b\x32\x12.telemetry.Payload\x12!\n\x08\x64istance\x18\x07 \x01(\x0b\x32\x0f.cache.Distance\x1a\x38\n\x08LogEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.log.Payload:\x02\x38\x01\"~\n\x0bRecordBatch\x12\x30\n\x07records\x18\x01 \x03(\x0b\x32\x1f.cache.RecordBatch.RecordsEntry\x1a=\n\x0cRecordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.cache.Record:\x02\x38\x01\x42\x30Z.github.com/tobiasfriden/dmc-server/proto/cacheb\x06proto3')
  ,
  dependencies=[proto_dot_action_dot_action__pb2.DESCRIPTOR,proto_dot_control_dot_control__pb2.DESCRIPTOR,proto_dot_mission_dot_mission__pb2.DESCRIPTOR,proto_dot_status_dot_status__pb2.DESCRIPTOR,proto_dot_log_dot_log__pb2.DESCRIPTOR,proto_dot_telemetry_dot_telemetry__pb2.DESCRIPTOR,])




_DISTANCE = _descriptor.Descriptor(
  name='Distance',
  full_name='cache.Distance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='droneId', full_name='cache.Distance.droneId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='otherId', full_name='cache.Distance.otherId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='master', full_name='cache.Distance.master', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='cache.Distance.value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=275,
)


_RECORD_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='cache.Record.LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cache.Record.LogEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='cache.Record.LogEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=591,
)

_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='cache.Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='cache.Record.action', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='control', full_name='cache.Record.control', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mission', full_name='cache.Record.mission', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='cache.Record.status', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log', full_name='cache.Record.log', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='telemetry', full_name='cache.Record.telemetry', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='cache.Record.distance', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RECORD_LOGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=591,
)


_RECORDBATCH_RECORDSENTRY = _descriptor.Descriptor(
  name='RecordsEntry',
  full_name='cache.RecordBatch.RecordsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cache.RecordBatch.RecordsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='cache.RecordBatch.RecordsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=658,
  serialized_end=719,
)

_RECORDBATCH = _descriptor.Descriptor(
  name='RecordBatch',
  full_name='cache.RecordBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='cache.RecordBatch.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RECORDBATCH_RECORDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=719,
)

_RECORD_LOGENTRY.fields_by_name['value'].message_type = proto_dot_log_dot_log__pb2._PAYLOAD
_RECORD_LOGENTRY.containing_type = _RECORD
_RECORD.fields_by_name['action'].message_type = proto_dot_action_dot_action__pb2._PAYLOAD
_RECORD.fields_by_name['control'].message_type = proto_dot_control_dot_control__pb2._PAYLOAD
_RECORD.fields_by_name['mission'].message_type = proto_dot_mission_dot_mission__pb2._PAYLOAD
_RECORD.fields_by_name['status'].message_type = proto_dot_status_dot_status__pb2._PAYLOAD
_RECORD.fields_by_name['log'].message_type = _RECORD_LOGENTRY
_RECORD.fields_by_name['telemetry'].message_type = proto_dot_telemetry_dot_telemetry__pb2._PAYLOAD
_RECORD.fields_by_name['distance'].message_type = _DISTANCE
_RECORDBATCH_RECORDSENTRY.fields_by_name['value'].message_type = _RECORD
_RECORDBATCH_RECORDSENTRY.containing_type = _RECORDBATCH
_RECORDBATCH.fields_by_name['records'].message_type = _RECORDBATCH_RECORDSENTRY
DESCRIPTOR.message_types_by_name['Distance'] = _DISTANCE
DESCRIPTOR.message_types_by_name['Record'] = _RECORD
DESCRIPTOR.message_types_by_name['RecordBatch'] = _RECORDBATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Distance = _reflection.GeneratedProtocolMessageType('Distance', (_message.Message,), dict(
  DESCRIPTOR = _DISTANCE,
  __module__ = 'proto.cache.cache_pb2'
  # @@protoc_insertion_point(class_scope:cache.Distance)
  ))
_sym_db.RegisterMessage(Distance)

Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), dict(

  LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), dict(
    DESCRIPTOR = _RECORD_LOGENTRY,
    __module__ = 'proto.cache.cache_pb2'
    # @@protoc_insertion_point(class_scope:cache.Record.LogEntry)
    ))
  ,
  DESCRIPTOR = _RECORD,
  __module__ = 'proto.cache.cache_pb2'
  # @@protoc_insertion_point(class_scope:cache.Record)
  ))
_sym_db.RegisterMessage(Record)
_sym_db.RegisterMessage(Record.LogEntry)

RecordBatch = _reflection.GeneratedProtocolMessageType('RecordBatch', (_message.Message,), dict(

  RecordsEntry = _reflection.GeneratedProtocolMessageType('RecordsEntry', (_message.Message,), dict(
    DESCRIPTOR = _RECORDBATCH_RECORDSENTRY,
    __module__ = 'proto.cache.cache_pb2'
    # @@protoc_insertion_point(class_scope:cache.RecordBatch.RecordsEntry)
    ))
  ,
  DESCRIPTOR = _RECORDBATCH,
  __module__ = 'proto.cache.cache_pb2'
  # @@protoc_insertion_point(class_scope:cache.RecordBatch)
  ))
_sym_db.RegisterMessage(RecordBatch)
_sym_db.RegisterMessage(RecordBatch.RecordsEntry)


DESCRIPTOR._options = None
_RECORD_LOGENTRY._options = None
_RECORDBATCH_RECORDSENTRY._options = None
# @@protoc_insertion_point(module_scope)
