# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sim/sim.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/sim/sim.proto',
  package='sim',
  syntax='proto3',
  serialized_options=_b('Z,github.com/tobiasfriden/dmc-server/proto/sim'),
  serialized_pb=_b('\n\x13proto/sim/sim.proto\x12\x03sim\"\x19\n\x07Payload\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x42.Z,github.com/tobiasfriden/dmc-server/proto/simb\x06proto3')
)




_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='sim.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='active', full_name='sim.Payload.active', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'proto.sim.sim_pb2'
  # @@protoc_insertion_point(class_scope:sim.Payload)
  ))
_sym_db.RegisterMessage(Payload)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
