# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/models/models.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dmc.proto.action import action_pb2 as proto_dot_action_dot_action__pb2
from dmc.proto.status import status_pb2 as proto_dot_status_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/models/models.proto',
  package='models',
  syntax='proto3',
  serialized_options=_b('Z/github.com/tobiasfriden/dmc-server/proto/models'),
  serialized_pb=_b('\n\x19proto/models/models.proto\x12\x06models\x1a\x19proto/action/action.proto\x1a\x19proto/status/status.proto\"\xe1\x01\n\x05\x44rone\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05orgId\x18\x03 \x01(\t\x12.\n\x0e\x66\x61ilSafeConfig\x18\x04 \x03(\x0b\x32\x16.models.FailSafeAction\x12\x1f\n\x06status\x18\x05 \x01(\x0b\x32\x0f.status.Payload\x12 \n\x04type\x18\x07 \x01(\x0e\x32\x12.models.Drone.Type\"<\n\x04Type\x12\n\n\x06\x41\x65rial\x10\x00\x12\r\n\tLandBased\x10\x01\x12\n\n\x06Marine\x10\x02\x12\r\n\tSubmarine\x10\x03\"C\n\x0e\x46\x61ilSafeAction\x12\"\n\x04Type\x18\x01 \x01(\x0e\x32\x14.action.Payload.Type\x12\r\n\x05\x41\x66ter\x18\x02 \x01(\x02\"D\n\x08Launcher\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05orgId\x18\x03 \x01(\t\x12\x0f\n\x07\x64roneId\x18\x04 \x01(\t\"~\n\x04Meta\x12\r\n\x05model\x18\x01 \x01(\t\x12\'\n\x08velocity\x18\x02 \x01(\x0b\x32\x15.models.Meta.Velocity\x1a>\n\x08Velocity\x12\n\n\x02VS\x18\x01 \x01(\x02\x12\x0b\n\x03VME\x18\x02 \x01(\x02\x12\x0b\n\x03VMD\x18\x03 \x01(\x02\x12\x0c\n\x04VMAX\x18\x04 \x01(\x02\x42\x31Z/github.com/tobiasfriden/dmc-server/proto/modelsb\x06proto3')
  ,
  dependencies=[proto_dot_action_dot_action__pb2.DESCRIPTOR,proto_dot_status_dot_status__pb2.DESCRIPTOR,])



_DRONE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='models.Drone.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Aerial', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LandBased', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Marine', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Submarine', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=257,
  serialized_end=317,
)
_sym_db.RegisterEnumDescriptor(_DRONE_TYPE)


_DRONE = _descriptor.Descriptor(
  name='Drone',
  full_name='models.Drone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='models.Drone.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='models.Drone.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orgId', full_name='models.Drone.orgId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failSafeConfig', full_name='models.Drone.failSafeConfig', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='models.Drone.status', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='models.Drone.type', index=5,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DRONE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=317,
)


_FAILSAFEACTION = _descriptor.Descriptor(
  name='FailSafeAction',
  full_name='models.FailSafeAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='models.FailSafeAction.Type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='After', full_name='models.FailSafeAction.After', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=386,
)


_LAUNCHER = _descriptor.Descriptor(
  name='Launcher',
  full_name='models.Launcher',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='models.Launcher.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='models.Launcher.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orgId', full_name='models.Launcher.orgId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='droneId', full_name='models.Launcher.droneId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=456,
)


_META_VELOCITY = _descriptor.Descriptor(
  name='Velocity',
  full_name='models.Meta.Velocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VS', full_name='models.Meta.Velocity.VS', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VME', full_name='models.Meta.Velocity.VME', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VMD', full_name='models.Meta.Velocity.VMD', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VMAX', full_name='models.Meta.Velocity.VMAX', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=522,
  serialized_end=584,
)

_META = _descriptor.Descriptor(
  name='Meta',
  full_name='models.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='models.Meta.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='models.Meta.velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_META_VELOCITY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=584,
)

_DRONE.fields_by_name['failSafeConfig'].message_type = _FAILSAFEACTION
_DRONE.fields_by_name['status'].message_type = proto_dot_status_dot_status__pb2._PAYLOAD
_DRONE.fields_by_name['type'].enum_type = _DRONE_TYPE
_DRONE_TYPE.containing_type = _DRONE
_FAILSAFEACTION.fields_by_name['Type'].enum_type = proto_dot_action_dot_action__pb2._PAYLOAD_TYPE
_META_VELOCITY.containing_type = _META
_META.fields_by_name['velocity'].message_type = _META_VELOCITY
DESCRIPTOR.message_types_by_name['Drone'] = _DRONE
DESCRIPTOR.message_types_by_name['FailSafeAction'] = _FAILSAFEACTION
DESCRIPTOR.message_types_by_name['Launcher'] = _LAUNCHER
DESCRIPTOR.message_types_by_name['Meta'] = _META
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Drone = _reflection.GeneratedProtocolMessageType('Drone', (_message.Message,), dict(
  DESCRIPTOR = _DRONE,
  __module__ = 'proto.models.models_pb2'
  # @@protoc_insertion_point(class_scope:models.Drone)
  ))
_sym_db.RegisterMessage(Drone)

FailSafeAction = _reflection.GeneratedProtocolMessageType('FailSafeAction', (_message.Message,), dict(
  DESCRIPTOR = _FAILSAFEACTION,
  __module__ = 'proto.models.models_pb2'
  # @@protoc_insertion_point(class_scope:models.FailSafeAction)
  ))
_sym_db.RegisterMessage(FailSafeAction)

Launcher = _reflection.GeneratedProtocolMessageType('Launcher', (_message.Message,), dict(
  DESCRIPTOR = _LAUNCHER,
  __module__ = 'proto.models.models_pb2'
  # @@protoc_insertion_point(class_scope:models.Launcher)
  ))
_sym_db.RegisterMessage(Launcher)

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(

  Velocity = _reflection.GeneratedProtocolMessageType('Velocity', (_message.Message,), dict(
    DESCRIPTOR = _META_VELOCITY,
    __module__ = 'proto.models.models_pb2'
    # @@protoc_insertion_point(class_scope:models.Meta.Velocity)
    ))
  ,
  DESCRIPTOR = _META,
  __module__ = 'proto.models.models_pb2'
  # @@protoc_insertion_point(class_scope:models.Meta)
  ))
_sym_db.RegisterMessage(Meta)
_sym_db.RegisterMessage(Meta.Velocity)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
